### ISSUE TITLE
line 300, in _compile     raise TypeError("first argument must be string or compiled pattern")

### ISSUE THREAD

**Issue by darkbunny** [tum-lkn/tcgui#18] opened 2021-06-20 19:35 UTC
`python3 main.py --ip 192.168.0.69 --port 5000
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    pattern = re.compile(args.regex)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 300, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
`

**Comment by hofbi** [comment] 2021-06-20 19:41
Thank you for reporting. I just fixed this issue 10 minutes ago so this should be a duplicate of #17 

Please try the latest master (10 minutes old). There this issue should be fixed.

**Comment by hofbi** [comment] 2021-06-22 09:45
I'll close this for now. Please reopen in case the error still appears on the latest version

**Closed by hofbi** 2021-06-22 09:45 UTC
